listening-port=3478
min-port=50000
max-port=50050

realm=lab.vn.ua
external-ip=79.143.43.173
listening-ip=0.0.0.0
relay-ip=0.0.0.0

user=TURN_USERNAME_HERE:TURN_PASSWORD_HERE

lt-cred-mech
no-tls
no-dtls
log-file=stdout