"""add_tunnel_url_to_kvm_nodes

Revision ID: 2ad3ae93f7d4
Revises: cbb21d03a828
Create Date: 2026-03-09 11:53:04.963684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad3ae93f7d4'
down_revision: Union[str, None] = 'cbb21d03a828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kvm_nodes', sa.Column('tunnel_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kvm_nodes', 'tunnel_url')
    # ### end Alembic commands ###
