"""add_mediamtx_auth_fields

Revision ID: 2ea57419c19d
Revises: 2ad3ae93f7d4
Create Date: 2026-03-27 10:42:53.793349

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea57419c19d'
down_revision: Union[str, None] = '2ad3ae93f7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kvm_nodes', sa.Column('mediamtx_user', sqlmodel.sql.sqltypes.AutoString(length=64), server_default='admin', nullable=False))
    op.add_column('kvm_nodes', sa.Column('mediamtx_pass', sqlmodel.sql.sqltypes.AutoString(length=64), server_default='password', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kvm_nodes', 'mediamtx_pass')
    op.drop_column('kvm_nodes', 'mediamtx_user')
    # ### end Alembic commands ###