"""Add stream_name

Revision ID: cbb21d03a828
Revises: df10e8cd76ec
Create Date: 2026-03-06 20:53:47.233961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb21d03a828'
down_revision: Union[str, None] = 'df10e8cd76ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kvm_nodes', sa.Column('stream_name', sa.String(length=64), server_default='kvm', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kvm_nodes', 'stream_name')
    # ### end Alembic commands ###
