"""Add machine_info and screenshot

Revision ID: df10e8cd76ec
Revises: 669f040232ec
Create Date: 2026-03-06 20:34:02.688552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df10e8cd76ec'
down_revision: Union[str, None] = '669f040232ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kvm_nodes', sa.Column('machine_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('kvm_nodes', sa.Column('screenshot', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kvm_nodes', 'screenshot')
    op.drop_column('kvm_nodes', 'machine_info')
    # ### end Alembic commands ###
