"""
schemas/signaling.py

Pydantic models for WebRTC signaling API endpoints.

The Control Plane acts as a relay: it forwards SDP offers from the browser to
the MediaMTX instance running on the Raspberry Pi, then returns the SDP answer.
No external STUN/TURN servers are required — both endpoints are on the same
private tunnel network so host ICE candidates are used directly.
"""

from typing import Optional

from pydantic import BaseModel, Field


class SDPOffer(BaseModel):
    """SDP offer generated by the browser's RTCPeerConnection.

    Forwarded by the Control Plane to MediaMTX WHEP/WHIP endpoint.
    """

    sdp: str = Field(..., description="Session Description Protocol offer string.")
    type: str = Field(default="offer", examples=["offer"])


class SDPAnswer(BaseModel):
    """SDP answer returned by MediaMTX, proxied back to the browser."""

    sdp: str = Field(..., description="Session Description Protocol answer string.")
    type: str = Field(default="answer", examples=["answer"])


class ICECandidate(BaseModel):
    """Trickle ICE candidate (optional — not required for host-only networks,
    but kept for compatibility with standard WebRTC negotiation flows)."""

    candidate: str
    sdp_mid: Optional[str] = None
    sdp_mline_index: Optional[int] = None
    username_fragment: Optional[str] = None
